update

diff --git a/chkfw b/chkfw
--- a/chkfw
+++ b/chkfw
@@ -1,7 +1,7 @@
 #!/bin/bash
-#$Id: chkfw,v 1.97 2015/06/04 07:04:30 fulford Exp $
+#$Id: chkfw,v 1.98 2015/09/22 14:08:50 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/chkfw,v $
-# $Revision: 1.97 $
+# $Revision: 1.98 $
 # Author C W Fulford.
 # Copyright 2012 - 2013 (c) C W Fulford.
 # Licensed for public use under the LGPL.
@@ -9,7 +9,7 @@
 ###################################################################
 cmd=`basename $0`
 syntax="$0 [[-C] [-cc <email_copy>]  [-d] [-m <max_wait in minutes>] [-p #[,#...]] [-T] [-u|-U] [-v]] <hostname> |-h|-V"
-ver=`echo "$Id: chkfw,v 1.97 2015/06/04 07:04:30 fulford Exp $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: chkfw,v 1.98 2015/09/22 14:08:50 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 while [ $# -gt 0 ];do
 	case $1 in
 		-C) chkonly=:;shift;;
@@ -96,7 +96,9 @@ _alert (){
 		$email_rcpt </dev/null
 	   touch $txtsent
 	   [ $verbose ] && echo "$cmd: alert sent" >&2
-	   [ $log ] && logger -t $cmd-$host "$msg"
+	   [ $log ] && logger -t $cmd-$host "$msg" ||{
+		echo "$cmd failed $LINENO: logger -t $cmd-$host $msg" >&2
+		}
 }
 
 # function to check if target server up, $port available and ssh ok.
@@ -193,7 +195,10 @@ if _host_up;then
 	if _fwok ;then
 		[ $verbose ] && echo "$cmd: active fw matches $tmplt ok" >&2 
 		[ -f $fwchlog ] && rm $fwchlog
-		[ $log ]&& logger -t $cmd-$host "active fw matches $tmplt ok"
+		msg="active fw matches $tmplt ok"
+		[ $log ]&& logger -t $cmd-$host "$msg"||{
+			echo "$cmd failed $LINENO: logger -t $cmd-$host $msg">&2
+		}
 		fw_restore="no"
 	else
 		   msg=" - active FW differs from $tmplt see ${fwchlog} - $date."
