update

diff --git a/chkfw b/chkfw
--- a/chkfw
+++ b/chkfw
@@ -1,7 +1,7 @@
 #!/bin/bash
-#$Id: chkfw,v 1.102 2016/11/12 09:13:08 fulford Exp fulford $
+#$Id: chkfw,v 1.103 2016/11/12 09:25:12 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/chkfw,v $
-# $Revision: 1.102 $
+# $Revision: 1.103 $
 # Author C W Fulford.
 # Copyright 2012 - 2013 (c) C W Fulford.
 # Licensed for public use under the LGPL.
@@ -9,7 +9,7 @@
 ###################################################################
 cmd=`basename $0`
 syntax="$0 [[-C] [-cc <email_copy>]  [-d] [-m <max_wait in minutes>] [-p #[,#...]] [-T] [-u|-U] [-v]] <hostname> |-h|-V"
-ver=`echo "$Id: chkfw,v 1.102 2016/11/12 09:13:08 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: chkfw,v 1.103 2016/11/12 09:25:12 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 while [ $# -gt 0 ];do
 	case $1 in
 		-C) chkonly=:;shift;;
@@ -196,8 +196,10 @@ if _host_up;then
 		[ $verbose ] && echo "$cmd: active fw matches $tmplt ok" >&2 
 		[ -f $fwchlog ] && rm $fwchlog
 		msg="active fw matches $tmplt ok"
-		[ $log ]&& logger -t $cmd-$host "$msg"||{
-		     echo "$cmd failed $LINENO: logger -t $cmd-$host $msg">&2
+		[ $log ]&&{
+			logger -t $cmd-$host "$msg"||{
+		     		echo "$cmd failed $LINENO: logger -t $cmd-$host $msg">&2
+			}
 		}
 		fw_restore="no"
 	else
