update

diff --git a/chkfw b/chkfw
--- a/chkfw
+++ b/chkfw
@@ -1,7 +1,7 @@
 #!/bin/bash
-#$Id: chkfw,v 1.100 2015/09/22 14:20:31 fulford Exp fulford $
+#$Id: chkfw,v 1.101 2015/09/22 14:23:53 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/chkfw,v $
-# $Revision: 1.100 $
+# $Revision: 1.101 $
 # Author C W Fulford.
 # Copyright 2012 - 2013 (c) C W Fulford.
 # Licensed for public use under the LGPL.
@@ -9,7 +9,7 @@
 ###################################################################
 cmd=`basename $0`
 syntax="$0 [[-C] [-cc <email_copy>]  [-d] [-m <max_wait in minutes>] [-p #[,#...]] [-T] [-u|-U] [-v]] <hostname> |-h|-V"
-ver=`echo "$Id: chkfw,v 1.100 2015/09/22 14:20:31 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: chkfw,v 1.101 2015/09/22 14:23:53 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 while [ $# -gt 0 ];do
 	case $1 in
 		-C) chkonly=:;shift;;
@@ -197,11 +197,11 @@ if _host_up;then
 		[ -f $fwchlog ] && rm $fwchlog
 		msg="active fw matches $tmplt ok"
 		[ $log ]&& logger -t $cmd-$host "$msg"||{
-			echo "$cmd failed $LINENO: logger -t $cmd-$host $msg">&2
+		     echo "$cmd failed $LINENO: logger -t $cmd-$host $msg">&2
 		}
 		fw_restore="no"
 	else
-		   msg=", active FW differs from $tmplt see ${fwchlog} $date."
+		   msg="active FW differs from $tmplt see ${fwchlog} $date."
 		   echo "$msg"| _alert &
 	   	   [ $verbose ] && echo "$cmd $msg" >&2
 	   	   fw_restore=:
